### ISSUE TITLE
UPI External adapter

### ISSUE THREAD

**Issue by PatrickAlphaC** [unipeer/unipeer#2]
Hi team!

Awesome project here. We'd love to have your UPI external adapter featured on market.link! https://market.link/search/adapters

Would you like to update it there? It's a great chance to help other engineers and show off your stuff!

**Comment by shalzz** [comment]
Hi,

Thanks @PatrickAlphaC, Yes we do have plans of open sourcing the External Adapter and listing it on market.link as soon as we have launched and have sanitized the repo to make sure there aren't any credentials left over in the git tree.

I'll update this issue when we do have an update.

**Comment by PatrickAlphaC** [comment]
Awesome, looking forward to it!

**Comment by shalzz** [comment]
Hey, 

I've gone ahead and made the adapter public at https://github.com/unipeer/chainlink-upi-adapter and listed it on market.link as well.
https://market.link/adapters/19d3b9c7-16ce-4f9b-a2e9-74ccccfbaf18?network=1

**Comment by PatrickAlphaC** [comment]
Awesome work! This is really cool!
